@request = {{$dotenv hostname}}/book
@bearerToken = {{$dotenv bearerStore}}


### Get All Books
GET {{request}}

### Get book detail [Pass book name with dash]
@bookName = A-Man-with-One-of-Those-Faces
GET {{request}}/{{bookName}}


### Add new book
POST {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "title":"A Man with One of Those Faces",
    "author":"Caimh Mcdonnell",
    "isbn": "1234657891",
    "synopsis":"Hello world",
    "price":240,
    "releasedYear": 2002
}


### Update Book detail
PUT {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "quantity": 10,
    "tags": ["Legend"],
    "_id": "60e43c527ae7e6794daa09f1",
    "title": "Book 15",
    "author": "Phyllis Glover",
    "isbn": "1234657891",
    "synopsis": "Ford History",
    "price": 200,
    "releasedYear": 2012
}

### Delete Book By ID
DELETE {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "_id": "60e43c527ae7e6794daa09f1"
}