@request = {{$dotenv hostname}}/book
@bearerToken = {{$dotenv bearerStore}}

### Get All Books
GET {{request}}

### Get book detail [Pass slug book name]
@bookName = the-art-oF-wAr
GET {{request}}/{{bookName}}


### Get book by author name [Pass slug author name]
@authorName = hira-Boi
GET {{request}}/author/{{authorName}}

### Get Book by ISBN
GET {{request}}/isbn/984500

### Get latest books
GET {{request}}/latest

### Add new book
POST {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "title":"Natural Education Volume 3",
    "author":"Milan",
    "isbn": "984500",
    "synopsis":"Don Quixote has become so entranced reading tales of chivalry that he decides to turn knight errant himself. In the company of his faithful squire, Sancho Panza, these exploits blossom in all sorts of wonderful ways. While Quixote's fancy often leads him astray—he tilts at windmills, imagining them to be giants—Sancho acquires cunning and a certain sagacity. Sane madman and wise fool, they roam the world together-and together they have haunted readers' imaginations for nearly four hundred years.",
    "price":260,
    "releasedYear": 2006
}


### Update Book detail
PUT {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "quantity": 10,
    "tags": ["Legend"],
    "_id": "60e43c527ae7e6794daa09f1",
    "title": "Book 15",
    "author": "Phyllis Glover",
    "isbn": "1234657891",
    "synopsis": "Ford History",
    "price": 200,
    "releasedYear": 2012
}

### Delete Book By ID
DELETE {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "_id": "60e43c527ae7e6794daa09f1"
}