@request = {{$dotenv hostname}}/order

### Get Order
GET {{request}}
Authorization: Bearer {{$dotenv bearerStore}}

### Place Order
POST {{request}}
Content-Type: application/json
Authorization: Bearer {{$dotenv bearerUser}}

{
    "orderBook": [{"bookId": "612d09b6dc66860f808be2a1","qty": 1,"price": 900},{"bookId": "612d0a80dc66860f808be2a5","qty": 1,"price": 900},{"bookId": "612f1d18fbf0d436cd150e09","qty": 1,"price": 900}, {"bookId": "612f11bffbf0d436cd150de5","qty": 1,"price": 520}]
}