@request = {{$dotenv hostname}}/review
@bearerToken = {{$dotenv bearerUser}}


### Get all reviews by bookid
GET {{request}}/612d0a31dc66860f808be2a3

### Insert New review
POST {{request}}/612d0a31dc66860f808be2a3
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "rating": 5,
    "description": "Best Book Ever"
}