@request = {{$dotenv hostname}}/review
@bearerToken = {{$dotenv bearerUser}}


### Get all reviews
GET {{request}}

### Get all reviews by bookid
GET {{request}}/60ee68dc51b0ea44244fddbe

### Insert New review
POST {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "book": "60ee68dc51b0ea44244fddbe",
    "rating": 3,
    "description": "Review 8 here"
}