@request = {{$dotenv hostname}}/store
@bearerToken = {{$dotenv bearerStore}}

### Register new store
POST {{request}}/register
Content-Type: application/json

{
    "email": "admin@everest.com",
    "password": "123456",
    "phone": "9898989898",
    "manager": "Admin admin",
    "latitude": "27.695410573378158",
    "longitude": "84.42346769727541",
    "branch": "Main",
    "showOnMap": true
}


### Login new store
POST {{request}}/login
Content-Type: application/json

{
    "email": "admin@everest.com",
    "password": "123456"
}


### Store Profile 
GET {{request}}/profile
Content-Type: application/json
Authorization: Bearer {{bearerToken}}