@request = {{$dotenv hostname}}/user
@bearerToken = {{$dotenv bearerUser}}

### Register new user
POST {{request}}/register
Content-Type: application/json

{
    "email": "user1@everest.com",
    "firstname": "Point",
    "lastname": "Pin",
    "address": "Lumbini, Nepal",
    "phone": "9898989898",
    "password": "password123"
}

### Login user
POST {{request}}/login
Content-Type: application/json

{
    "email": "user1@everest.com",
    "password": "password123"
}

### User Profile 
GET {{request}}/profile
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


### User Update
PUT {{request}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "firstname": "Derek",
    "lastname": "Lubowitz",
    "address": "85317",
    "phone": "98989898",
    "birthdate": "2012-01-11T18:15:00.000Z",
    "gender": "male"
}

### View cart
GET {{request}}/cart
Authorization: Bearer {{bearerToken}}

### Add to cart
POST {{request}}/addtocart/611cadcadb43cb0d905ee59a
Authorization: Bearer {{bearerToken}}
